- Leanplum-SDK/Classes/LPNetworkOperation.m
- Leanplum-SDK/Classes/LeanplumRequest.m
This is required from the server so that it can detect duplicates
> perf(request): Send requests in order

- Leanplum-SDK/Classes/LPEventCallbackManager.m
- Leanplum-SDK/Classes/LPMessageTemplates.m
- Leanplum-SDK/Classes/Leanplum.m
This commit ensures UI, start/track call, callbacks are done on main thread.
> Fix/iam on background/lp 5794

- Example/Tests/Classes/EventDataManagerTest.m
- Example/Tests/Classes/NewsfeedTest.m
- Leanplum-SDK/Classes/LPEventCallbackManager.m
> fix(network): Callbacks were not called in some situations

- Leanplum-SDK/Classes/LPMessageTemplates.m
Use the newer openURL for iOS10+
> fix(message): Fix openURL freeze on iOS10

- Leanplum-SDK/Classes/LPDatabase.m
Fixes possible sporadic/rare multithreading issues around sqlite db.
- Set Sqlite config to use serialized mode.
- Open DB connection using full mutex/serialized mode.
- Adds try/catch around method implementation
> refactor(sqlite): add possible failure handling around sqlite multithreading

- Leanplum-SDK/Classes/LPMessageTemplates.m
>  fix(message): HTML Y inconsistency with iPhoneX on bottom aligned

- Example/Leanplum-SDK.xcodeproj/project.pbxproj
- Example/Leanplum-SDK.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Example/Tests/Classes/MessagesTest.m
- Leanplum-SDK/Classes/LPActionManager.h
- Leanplum-SDK/Classes/LPActionManager.m
- Leanplum-SDK/Classes/Leanplum.m
- check for startTime and endTime for each message
- display message only if between startTime and endTime
> feat: Active Period check for in-app messages

- Leanplum-SDK/Classes/LPMessageTemplates.m
> fix(iPhone X): Fix for bottom area padding for accept button on iPhone X.

- Leanplum-SDK/Classes/LPMessageTemplates.m
> bug: fix url encoding for strings

- Example/Tests/Classes/ActionManagerTest.m
> test(active_period): add active period actionmanager test

- Leanplum-SDK/Classes/LPMessageTemplates.m
> Fix/html inapp iphonex landscape/e2 162

- Example/Tests/Classes/UtilitiesTest.m
- Leanplum-SDK/Classes/LPMessageTemplates.m
- Leanplum-SDK/Classes/Utils.h
- Leanplum-SDK/Classes/Utils.m
URL encoding was not working as expected. Did more research and used solution based off of : https://useyourloaf.com/blog/how-to-percent-encode-a-url-string/
Added tests as well
> Fix URL encoding

- Leanplum-iOS-SDK.podspec
> Merge master to develop

- Leanplum-iOS-SDK.podspec
> Master merge to develop

- Leanplum-SDK/Classes/LPFeatureFlagManager.h
- Leanplum-SDK/Classes/LPFeatureFlagManager.m
Add the basic interface for feature flagging on the SDK. More detailed implementation to follow
> add feature flag manager boilerplate

- Leanplum-SDK/Classes/Features/Variables/LPVarCache.h
- Leanplum-SDK/Classes/Features/Variables/LPVarCache.m
- Leanplum-SDK/Classes/Internal/Leanplum.m
- Leanplum-SDK/Classes/Leanplum.h
When a user logs out of an app, we need to clear any stale content for the previously logged in user. This adds a method to do that
> E2-1537: add method to clear content

- Leanplum-SDK/Classes/LPVar.h
- Leanplum-SDK/Classes/Leanplum.h
- build.sh
Extract header file into its own file to clean up Leanplum.h
> extract lpvar from leanplum.h

- Example/Tests/Classes/LPCountAggregatorTest.m
- Leanplum-SDK/Classes/Managers/LPCountAggregator.m
> Counting on Client

- Leanplum-SDK/Classes/Managers/Networking/LPRequestSender.m
- Leanplum-SDK/Classes/Managers/Networking/LeanplumRequest.m
> send all counts

- .travis.yml
> master branch build

- .travis.yml
- Example/Podfile
- Leanplum-iOS-SDK-source.podspec
- Tools/push.sh
> add travis cd

- Leanplum-iOS-SDK-source.podspec
- Leanplum-iOS-SDK.podspec
- Tools/push.sh
We have Leanplum-iOS-SDK (packaged framework) and Leanplum-iOS-SDK-source (open source).
We are moving the packaged framework to also deliver the source files through the podfile
> iOS Release

- Example/Tests/Classes/LeanplumTest.m
- Leanplum-SDK/Classes/Internal/LPInternalState.h
- Leanplum-SDK/Classes/Internal/LPInternalState.m
- Leanplum-SDK/Classes/Internal/Leanplum.m
- Leanplum-SDK/Classes/Leanplum.h
- Leanplum-SDK/Classes/Models/LPMessageArchiveData.h
- Leanplum-SDK/Classes/Models/LPMessageArchiveData.m
https://leanplum.atlassian.net/browse/E2-1658
In order to let the client know an in-app message is shown, we need to expose a callback for developers to hook into.
> callback on message displayed

- .travis.yml
- Leanplum-iOS-SDK-source.podspec
- Leanplum-iOS-SDK.podspec
- build.sh
Build the binary and upload to github releases when tagged
> Automate build and deploy of binary

- Example/Tests/Classes/LeanplumTest.m
- Leanplum-SDK/Classes/Internal/EnumConstants.h
- Leanplum-SDK/Classes/Internal/EnumConstants.m
- Leanplum-SDK/Classes/Internal/Leanplum.m
- Leanplum-SDK/Classes/Leanplum.h
- Leanplum-SDK/Classes/Managers/Networking/LPRequestFactory.h
- Leanplum-SDK/Classes/Managers/Networking/LPRequestFactory.m
https://leanplum.atlassian.net/secure/RapidBoard.jspa?rapidView=28&projectKey=E2&modal=detail&selectedIssue=LP-10023
> E2-10023 add trackGeofence

- Leanplum-SDK/Classes/LPMessageTemplates.m
> Using safe area insets on ios 11 and higher

- Example/Tests/Classes/LeanplumTest.m
- Example/Tests/Resources/Responses/simple_start_response.json
- Leanplum-SDK/Classes/Internal/Leanplum.m
Code fix is committed. But, testing is still going on with different settings. So, its WIP.
Fixes #
- Allow multiple messages for same priority
- Only display 1 message if same priority and delay.
-
-
-
> LP-10041: Murka support multiple messages for same priority and show 

- Example/Leanplum-SDK.xcodeproj/project.pbxproj
- Example/Tests/Classes/MessagesTest.m
- Example/Tests/Resources/TestData/TiedPrioritiesDifferentDelay.json
- Leanplum-SDK/Classes/Internal/Leanplum.m
Fixes #
Extra test cases and improvement.
-
-
-
> extra tests

- Example/Tests/Classes/LPRequestSenderTest.m
- Leanplum-SDK.xcodeproj/project.pbxproj
- Leanplum-SDK/Classes/Features/Actions/LPActionManager.m
- Leanplum-SDK/Classes/Features/Inbox/LPInbox.m
- Leanplum-SDK/Classes/Features/Variables/LPVarCache.m
- Leanplum-SDK/Classes/Internal/LPConstants.m
- Leanplum-SDK/Classes/Internal/Leanplum.m
- Leanplum-SDK/Classes/Managers/Networking/LPRequestSender.h
- Leanplum-SDK/Classes/Managers/Networking/LPRequestSender.m
> fix incorrect method name

- Leanplum-SDK.xcodeproj/project.pbxproj
- Leanplum-SDK/Classes/Features/Variables/LPVarCache.m
- Leanplum-SDK/Classes/Managers/LPFileManager.m
- Leanplum-SDK/Classes/Managers/Networking/LPFileTransferManager.h
- Leanplum-SDK/Classes/Managers/Networking/LPFileTransferManager.m
- Leanplum-SDK/Classes/Managers/Networking/LPRequestFactory.m
The refactor work from LeanplumRequest to LPRequest is protected behind a feature flag. However, the methods that deal with file upload / download was punted to its own class and the new class was not written. This adds the new class and the usage in the relevant places.
> File upload download manager

- Leanplum-SDK/Classes/Internal/LPEnumConstants.h
- Leanplum-SDK/Classes/Managers/LPCountAggregator.h
> Using include instead of import

- Leanplum-SDK/Classes/Internal/Leanplum.m
> Adding cache update if variants are changed

- Example/Tests/Classes/LeanplumTest.m
- Leanplum-SDK/Classes/Internal/FeatureFlag/LPFeatureFlags.h
- Leanplum-SDK/Classes/Internal/LPConstants.h
- Leanplum-SDK/Classes/Managers/Networking/LPFileTransferManager.m
- Leanplum-SDK/Classes/Managers/Networking/LPNetworkEngine.m
- Leanplum-SDK/Classes/Managers/Networking/LPRequestSender.h
- Leanplum-SDK/Classes/Managers/Networking/LPRequestSender.m
- Leanplum-SDK/Classes/Managers/Networking/LeanplumRequest.m
- Leanplum-SDK/Classes/Utilities/LPUtils.h
- Leanplum-SDK/Classes/Utilities/LPUtils.m
Fixes #
Added Gzip support to request.
- Added Gzip support to the request. There will be gzip encoding type on every request call, even if the server supports gzip compression or not. And client should gracefully handle the successful response.
-
-
> Lp 10189 accept gzip

- Example/Leanplum-SDK.xcodeproj/project.pbxproj
- Leanplum-SDK/Classes/Features/Actions/LPActionContext.m
- Leanplum-SDK/Classes/Features/Actions/LPActionManager.m
- Leanplum-SDK/Classes/LPMessageTemplates.m
- Leanplum-SDK/Classes/Managers/Networking/LeanplumRequest.m
https://leanplum.atlassian.net/browse/LP-10318
> E2-1834: Address warnings 

- Leanplum-SDK/Classes/Features/Actions/LPActionManager.h
- Leanplum-SDK/Classes/Features/Actions/LPActionManager.m
- Leanplum-SDK/Classes/Internal/Leanplum.m
- Leanplum-SDK/Classes/LPMessageTemplates.m
> remove unneeded ios version checks

- Example/Tests/Classes/LPMessageTemplatesClassTest.m
- Leanplum-SDK/Classes/LPMessageTemplates.m
Fixes #
Fixes and issue which could cause push pre permission dialog to be shown even if user declined the native notification dialog.
> LP-10387 Disable PPP after user accepts/declines

- Leanplum-SDK/Classes/Internal/Leanplum.m
> add counters

- PULL_REQUEST_TEMPLATE.md
> change PR template

- Leanplum-SDK/Classes/Features/Actions/LPActionManager.m
JIRA Issue        | [E2-1883](https://leanplum.atlassian.net/browse/E2-1883)
People Involved   | @shivanshukumar 
Need to remove an event leads to inconsistent results on the dashboard
Remove event
None
Yes
> E2-1883: Remove displayed event 

- Leanplum-SDK/Classes/LPMessageTemplates.m
Customer wanted landscape rich interstitial to be full screen (not within iPhone safe area)
Update inset calculations for iPhoneX and above, update formatting option for Scrollview within webview for proper format results
tested landscape mode for pre iPhoneX and post iPhoneX to check rich interstitial still working properly
> Lp 10193 rich interstitial fullscreen

- Leanplum-SDK/Classes/Features/Actions/LPActionContext.m
- Leanplum-SDK/Classes/LPActionContext.h
- Leanplum-SDK/Classes/LPMessageTemplates.m
JIRA Issue        | [LP-10958](https://leanplum.atlassian.net/browse/LP-10958)
> Fixing an issue with WK not loading referenced resources.

- Example/Tests/Classes/LPFileManagerTest.m
- Leanplum-SDK/Classes/Managers/LPFileManager.h
- Leanplum-SDK/Classes/Managers/LPFileManager.m
- Leanplum-SDK/Classes/Utilities/LPDatabase.m
> E2-1227 Excluding database from iCloud/iTunes sync

- Leanplum-SDK/Classes/Utilities/Vendor/SocketIO/Leanplum_SocketIO.m
JIRA Issue        | [LP-10920](https://leanplum.atlassian.net/browse/LP-10920)
> Enabling use of TLS

- Leanplum-SDK/Classes/LPMessageTemplates.m
JIRA Issue        | [LP-11004](https://leanplum.atlassian.net/browse/LP-11004)
> [LP-11004] Fixing not hiding rich interstitial

- Leanplum-SDK/Classes/Features/Events/LPEventCallbackManager.m
- Leanplum-SDK/Classes/Managers/Networking/LPRequestSender.m
- Leanplum-SDK/Classes/Managers/Networking/LeanplumRequest.m
> [LP-10948] Potential fix for pause crash

- Leanplum-SDK/Classes/Utilities/Vendor/WebSocket/Leanplum_WebSocket.m
JIRA Issue        | [JIRA_TICKET_ID](https://leanplum.atlassian.net/browse/LP-11102)
> Removing exception when wss is used

- Leanplum-SDK/Classes/LPMessageTemplates.m
JIRA Issue        | [LP-11085](https://leanplum.atlassian.net/browse/LP-11085)
> Rich interstiail orientation fix

- Example/Podfile
- Leanplum-SDK/Classes/Features/Events/LPEventCallback.m
- Leanplum-SDK/Classes/Features/Events/LPEventCallbackManager.m
- Leanplum-SDK/Classes/Internal/Leanplum.m
JIRA Issue        | [LP-11142](https://leanplum.atlassian.net/browse/LP-11142)
> [LP-11142] Fixing a potential objc_release crash

- Leanplum-SDK/Classes/Internal/Leanplum.m
JIRA Issue        | [LP-11200](https://leanplum.atlassian.net/browse/LP-112000)
> [LP-11200] Synchronize access to callbacks

- Leanplum-SDK/Classes/Internal/Leanplum.m
JIRA Issue        | [JIRA_TICKET_ID](https://leanplum.atlassian.net/browse/LP-11199)
> [LP-11199] Fixing background deadlock

- Leanplum-SDK/Classes/Internal/Leanplum.m
JIRA Issue        | [LP-11206](https://leanplum.atlassian.net/browse/LP-11206)
> [LP-11206] Adding synchronization when performing actions

- Example/Leanplum-SDK.xcodeproj/project.pbxproj
- Example/Tests/Classes/LPActionContextTest.m
- Example/Tests/Classes/LPNetworkOperationTest.m
- Leanplum-SDK/Classes/Features/Actions/LPActionContext.m
- Leanplum-SDK/Classes/Features/Actions/LPUIAlert.h
- Leanplum-SDK/Classes/Features/Actions/LPUIAlert.m
- Leanplum-SDK/Classes/Managers/Networking/LPNetworkOperation.m
- Leanplum-SDK/Classes/MessageTemplates/LPAlertMessageTemplate.m
- Leanplum-SDK/Classes/MessageTemplates/LPCenterPopupMessageTemplate.m
- Leanplum-SDK/Classes/MessageTemplates/LPWebInterstitialMessageTemplate.m
- Leanplum-SDK/Classes/MessageTemplates/Views/LPHitView.h
> LP-11256 deal with all warnings

- Leanplum-SDK/Classes/Features/Actions/LPActionContext-Internal.h
- Leanplum-SDK/Classes/Features/Variables/LPVar-Internal.h
- Leanplum-SDK/Classes/Internal/LPEnumConstants.h
- Leanplum-SDK/Classes/LPActionArg.h
- Leanplum-SDK/Classes/LPActionContext.h
- Leanplum-SDK/Classes/LPInbox.h
- Leanplum-SDK/Classes/LPMessageTemplates.h
- Leanplum-SDK/Classes/LPVar.h
- Leanplum-SDK/Classes/Leanplum.h
- Leanplum-SDK/Classes/Managers/LPFileManager.m
JIRA Issue        | [LP-11127](https://leanplum.atlassian.net/browse/LP-11127)
> [LP-11127] Better swift support

- Leanplum-SDK/Classes/MessageTemplates/ViewControllers/LPWebInterstitialViewController.m
People Involved   | @milos1290 , @e7mac
> Fixing an issue with preprocessor macro

- Leanplum-SDK/Classes/MessageTemplates/ViewControllers/LPWebInterstitialViewController.m
> fix web background color

- Leanplum-SDK/Classes/Features/Actions/LPActionContext.m
- Leanplum-SDK/Classes/MessageTemplates/ViewControllers/LPWebInterstitialViewController.m
> Fix banner

- Leanplum-SDK/Classes/MessageTemplates/ViewControllers/LPMessageTemplateUtilities.m
JIRA Issue        | [QAQ-1767](https://leanplum.atlassian.net/browse/QAQ-1767)
> [QAQ-1767] Fixing chained iam not displayed

- Leanplum-SDK.xcodeproj/project.pbxproj
- Leanplum-SDK.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Leanplum-SDK.xcodeproj/xcshareddata/xcschemes/Leanplum-iOS-Example.xcscheme
- Leanplum-SDK.xcodeproj/xcshareddata/xcschemes/LeanplumSDK-iOS.xcscheme
Before, I wasn't able to import Leanplum framework in my project and this PR fix it.
> Fix carthage issue

- Leanplum-SDK.xcodeproj/project.pbxproj
> Exposing PN headers

- Leanplum-SDK/Classes/LPInbox.h
JIRA Issue        | [LP-11346](https://leanplum.atlassian.net/browse/LP-11346)
People Involved   | @milos1290 
Methods were causing issues on RN that are resolved by changing them to properties
> change method to properties

- Leanplum-SDK/Classes/Features/Actions/LPActionContext-Internal.h
- Leanplum-SDK/Classes/Features/Actions/LPActionContext.m
- Leanplum-SDK/Classes/LPActionContext.h
JIRA Issue        | [SDK-69](https://leanplum.atlassian.net/browse/SDK-69)
> Expose Action Context arguments and message id

- Example/Tests/Classes/LPPushNotificationsManagerTest.m
- Leanplum-SDK/Classes/Notifications/Push/LPPushNotificationsHandler.m
JIRA Issue        | [SDK-72](https://leanplum.atlassian.net/browse/SDK-72)
> SDK-72 iOS push types

- Example/Tests/Classes/LPCountAggregatorTest.m
Fix Mocked request propagation and clean up requests.
> Fix CountAggregator test

- Leanplum-SDK/Classes/Internal/Leanplum.m
JIRA Issue        | [SDK-161](https://leanplum.atlassian.net/browse/SDK-161)
> [SDK-161] Check options for nil

- Example/Tests/Classes/LPOpenUrlMessageTemplateTest.m
- Leanplum-SDK/Classes/MessageTemplates/LPOpenUrlMessageTemplate.m
JIRA Issue        | [SDK-227](https://leanplum.atlassian.net/browse/SDK-227)
> fix encoding + symbol

- Example/Tests/Classes/LPInboxTest.m
- Leanplum-SDK/Classes/Features/Inbox/LPInbox.m
- Leanplum-SDK/Classes/Internal/Leanplum.m
- Leanplum-SDK/Classes/Internal/LeanplumInternal.h
- Leanplum-SDK/Classes/LPInbox.h
JIRA Issue        | [SDK-231](https://leanplum.atlassian.net/browse/SDK-231)
> Download inbox messages

- Example/Leanplum-SDK.xcodeproj/project.pbxproj
- Example/Tests/Classes/LPRequestBatchTest.m
- Example/Tests/Classes/LPRequestSenderTimerTest.m
JIRA Issue        | [SDK-235](https://leanplum.atlassian.net/browse/SDK-235)
> Unit tests for request batching

- README.md
- Tools/triggerRN.sh
- Tools/triggerRondo.sh
JIRA Issue        | [SDK-135](https://leanplum.atlassian.net/browse/SDK-135)
> Update travis to .com

- Example/Leanplum-SDK.xcodeproj/project.pbxproj
- Leanplum-iOS-SDK.podspec
JIRA Issue        | [SDK-256](https://leanplum.atlassian.net/browse/SDK-256)
> Static linking fix

- Leanplum-SDK/Classes/Utilities/LPDatabase.m
JIRA Issue        | [SDK-228](https://leanplum.atlassian.net/browse/SDK-228)
> fix sqlite crash

- Example/Tests/Classes/LPActionManagerTest.m
- Example/Tests/Classes/LPUtilsTest.m
- Leanplum-SDK/Classes/Features/Actions/LPActionManager.m
- Leanplum-SDK/Classes/Utilities/LPUtils.h
- Leanplum-SDK/Classes/Utilities/LPUtils.m
JIRA Issue        | [SDK-354](https://leanplum.atlassian.net/browse/SDK-354)
> Fix for tracking events with bool as a parameter

- Leanplum-SDK/Classes/Features/Inbox/LPInbox.m
- Leanplum-SDK/Classes/Features/Variables/LPVarCache.m
- Leanplum-SDK/Classes/Internal/Leanplum.m
- Leanplum-SDK/Classes/MessageTemplates/LPOpenUrlMessageTemplate.m
- Leanplum-SDK/Classes/MessageTemplates/ViewControllers/LPWebInterstitialViewController.m
- Leanplum-SDK/Classes/Notifications/Local/LPLocalNotificationsHandler.m
- Leanplum-SDK/Classes/Notifications/Local/LPLocalNotificationsManager.m
- Leanplum-SDK/Classes/Notifications/Push/LPPushNotificationsHandler.m
- Leanplum-SDK/Classes/Notifications/Push/LPPushNotificationsManager.m
- Leanplum-SDK/Classes/Utilities/LPDatabase.m
- Leanplum-SDK/Classes/Utilities/LPUtils.h
- Leanplum-SDK/Classes/Utilities/LPUtils.m
JIRA Issue        | [SDK-245](https://leanplum.atlassian.net/browse/SDK-245)
> fixing deprecation warnings

- Leanplum-SDK/Classes/MessageTemplates/ViewControllers/LPWebInterstitialViewController.m
JIRA Issue        | [SDK-392](https://leanplum.atlassian.net/browse/SDK-392)
> checking for nil before loading file or request into webview

- Leanplum-SDK/Classes/Features/Actions/LPActionContext-Internal.h
- Leanplum-SDK/Classes/Features/Variables/LPVar-Internal.h
- Leanplum-SDK/Classes/LPActionContext.h
- Leanplum-SDK/Classes/LPVar.h
JIRA Issue        | [SDK-405](https://leanplum.atlassian.net/browse/SDK-405)
> moving methods from internal headers

- Leanplum-SDK/Classes/Notifications/Push/LPPushNotificationsHandler.m
JIRA Issue        | [SDK-451](https://leanplum.atlassian.net/browse/SDK-451)
> fix duplicate messages

- LeanplumSDK/LeanplumSDK/Classes/Managers/Networking/LPRequestSender.m
JIRA Issue        | [SDK-526](https://leanplum.atlassian.net/browse/SDK-526)
> Retry on response code 429

- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/ExceptionsTest.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/Extensions/LPNetworkOperation+Category.h
- LeanplumSDKApp/LeanplumSDKTests/Classes/Extensions/LPNetworkOperation+Category.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/Extensions/LPRequest+Extension.h
- LeanplumSDKApp/LeanplumSDKTests/Classes/Extensions/LPRequest+Extension.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/Extensions/LPRequestFactory+Extension.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/Extensions/LPRequestSender+Categories.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/Extensions/LeanplumReachability+Category.h
- LeanplumSDKApp/LeanplumSDKTests/Classes/Extensions/LeanplumReachability+Category.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/LPActionManagerTest.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/LPAppIconManagerTest.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/LPDeferMessageManagerTest.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/LPEventDataManagerTest.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/LPFileManagerTest.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/LPInboxTest.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/LPLocalCapsTest.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/LPRequestSenderTest.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/LeanplumNotificationsManagerTest.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/LeanplumSDKTests-Bridging-Header.h
- LeanplumSDKApp/LeanplumSDKTests/Classes/LeanplumTest.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/MessagesTest.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/Utilities/LeanplumHelper.h
- LeanplumSDKApp/LeanplumSDKTests/Classes/Utilities/LeanplumHelper.m
- LeanplumSDKApp/LeanplumSDKTests/Resources/Responses/Malformed/malformed_simple_start_response.json
- LeanplumSDKApp/LeanplumSDKTests/Resources/Responses/complex_start_response.json
- LeanplumSDKApp/LeanplumSDKTests/Resources/Responses/simple_start_response.json
- LeanplumSDKApp/LeanplumSDKTests/Resources/Responses/start_variables_response.json
- LeanplumSDKApp/LeanplumSDKTests/Resources/Responses/start_with_variant_debug_info_response.json
JIRA Issue        | [SDK-586](https://leanplum.atlassian.net/browse/SDK-586)
Improve Unit tests and helpers:
- Mocks
- Swizzling and restoring
- Waiters and Expectations
- Clean up and teardown
> Unit Tests Improvements

- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumNotificationsManager+Utils.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/UNNotificationSettings+LPUtil.swift
- LeanplumSDKApp/LeanplumSDKApp.xcodeproj/project.pbxproj
- LeanplumSDKApp/LeanplumSDKTests/Classes/LeanplumPushNotificationSettingsTest.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/LeanplumSDKTests-Bridging-Header.h
JIRA Issue        | [SDK-564](https://leanplum.atlassian.net/browse/SDK-564)
> Unit testing notification settings

- LeanplumSDK/LeanplumSDK/Classes/Internal/LPInternalState.h
- LeanplumSDKApp/LeanplumSDKApp.xcodeproj/project.pbxproj
- LeanplumSDKApp/LeanplumSDKTests/Classes/Extensions/LeanplumNotificationsManagerMock.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/LeanplumNotificationsManagerUtilsTest.swift
JIRA Issue        | [SDK-563](https://leanplum.atlassian.net/browse/SDK-563)
> Unit test notification manager utils

- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumNotificationSettings.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumNotificationsManager.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/LeanplumPushNotificationSettingsTest.swift
> refactor update settings to server

- LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/LPRichInterstitialMessageTemplate.h
- LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/LPRichInterstitialMessageTemplate.m
- LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/ViewControllers/LPMessageTemplateUtilities.h
- LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/ViewControllers/LPMessageTemplateUtilities.m
- LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/ViewControllers/LPWebInterstitialViewController.m
JIRA Issue        | [SDK-746](https://leanplum.atlassian.net/browse/SDK-746)
> [SDK-746] Present banner as child, enable interaction with parent

- LeanplumSDK/LeanplumSDK/Classes/Features/Inbox/LPInbox.m
JIRA Issue        | [SDK-750](https://leanplum.atlassian.net/browse/SDK-750)
> Fix inbox data save

- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager+Configuration.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager+Triggering.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager.swift
> Add IAM handlers documentation

- LeanplumSDK/LeanplumSDK/Classes/Features/Actions/LPActionContext.m
- LeanplumSDK/LeanplumSDK/Classes/Features/Actions/LPActionTriggerManager.m
- LeanplumSDK/LeanplumSDK/Classes/Features/Variables/LPVarCache.m
- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/Classes/Managers/Networking/LeanplumSocket.m
- LeanplumSDK/LeanplumSDK/Classes/Notifications/Local/LPLocalNotificationsManager.m
- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/LPActionContextTest.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/MessagesTest.m
Set Objective-C name to LPActionManager
> Objc LPActionManager

- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager+Executor.swift
> Do not perform actions if disabled

- LeanplumSDK/LeanplumSDK/Classes/Features/Actions/LPActionContext.m
- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager+Queue.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager.swift
JIRA Issue        | [SDK-1842](https://wizrocket.atlassian.net/browse/SDK-1842)
> Fix performActions when message open action is inserted

- LeanplumSDK/LeanplumSDK.xcodeproj/project.pbxproj
- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager+Triggering.swift
Addressing issue #495 
Add workaround based on proposal here:
https://github.com/apple/swift/issues/56573
> swift module ambiguity workaround

- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Notifications/NotificationsManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Notifications/Proxy/NotificationsProxy+Disabled.swift
Suppress deprecation warnings #494
> Suppress deprecation warnings

- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager.swift
JIRA Issue        | [SDK-1952](https://wizrocket.atlassian.net/browse/SDK-1952)
Perform actions when the queue is enabled if it was disabled before and if there are any actions in the queue.
1. Pause queue
2. Trigger actions
3. Disable queue
4. Unpause queue
5. Enabled queue - perform the actions that were added in the queue while it was paused
Check if `isEnabled` and the previous value was _disabled_.
> Perform actions when queue is enabled

- LeanplumSDK/LeanplumSDK/Classes/Managers/Networking/LPRequestSender.m
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager+Constants.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager+ResponseHandler.swift
> Fix migration hash

- LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/LPRichInterstitialMessageTemplate.m
JIRA Issue        | [SDK-2323](https://wizrocket.atlassian.net/browse/SDK-2323)
See JIRA and issue #523
> Fix banner presentation

- LeanplumSDKApp/LeanplumSDKApp.xcodeproj/project.pbxproj
- LeanplumSDKApp/LeanplumSDKTests/Classes/LPRequestSenderTest.m
> Fix duplicate files in project navigator

- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/LPRequestSenderTest.m
> Do not connect socket in prod mode

- .travis.yml
> Use Xcode 14 in Travis

- LeanplumSDK/LeanplumSDK.xcodeproj/project.pbxproj
- LeanplumSDK/LeanplumSDK/Classes/CleverTapInstanceCallback.h
- LeanplumSDK/LeanplumSDK/Classes/CleverTapInstanceCallback.m
- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/Classes/Leanplum.h
- LeanplumSDK/LeanplumSDK/Classes/LeanplumSDK.h
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager+API.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/CTWrapper.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/Wrapper.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/Migration/CTWrapperTest.swift
JIRA Issue        | [SDK-2424](https://wizrocket.atlassian.net/browse/SDK-2424)
Allow multiple CleverTap instance callbacks
> Support multiple CleverTap instance callbacks

- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/LPCTNotificationsManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager+API.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/CTWrapper.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/Wrapper.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Notifications/NotificationsManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Notifications/Proxy/NotificationsProxy.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/Notifications/NotificationsManagerMock.swift
JIRA Issue        | [SDK-2382](https://wizrocket.atlassian.net/browse/SDK-2382)
- Allow early initialization of CleverTap.
- Initialize CleverTap independently of Leanplum
> Allow early initialization of CleverTap

- Leanplum-iOS-SDK.podspec
- Package.swift
- Podfile
Bump to latest CT iOS SDK version.
> Bump CT version to 4.1.5

- LeanplumSDK/LeanplumSDK/Classes/Utilities/LPSwizzle.m
JIRA Issue        | [SDK-2433](https://wizrocket.atlassian.net/browse/SDK-2433)
> Fix LPSwizzle log

- LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/ViewControllers/LPMessageTemplateUtilities.h
- LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/ViewControllers/LPMessageTemplateUtilities.m
Refactor and remove dead code.
> Refactoring message templates utils

- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/LPCTNotificationsManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/CTWrapper.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Notifications/NotificationsManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Notifications/Proxy/NotificationsProxy+Swizzling.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Notifications/Proxy/NotificationsProxy.swift
Change log level to info for some loggings to get more data.
> Change log level to info to get more data

- Tools/build.sh
> Fix zipping

- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager.swift
JIRA Issue        | [SDK-2633](https://wizrocket.atlassian.net/browse/SDK-2633)
Fix lock if the first start is offline
Remove lock and call fetchMigrationStateAsync
> Fix lock on first offline start

- Leanplum-iOS-SDK.podspec
- Package.swift
- Podfile
JIRA Issue        | [SDK-2957](https://wizrocket.atlassian.net/browse/SDK-2957)
Update CleverTap SDK to 5.0.0
> Update CT SDK to 5.0.0

- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
> Use currentDevice model for simulators on arm64

- Tools/build.sh
JIRA Issue        | [MC-1621](https://wizrocket.atlassian.net/browse/MC-1621)
Codesign the xcframeworks.
References:
- [Verifying the origin of your XCFrameworks](https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks)
- [Sign the XCFramework bundle](https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle#Sign-the-XCFramework-bundle)
> Codesign xcframeworks

- Leanplum-iOS-SDK.podspec
- Package.swift
- Podfile
JIRA Issue        | [MC-1852](https://wizrocket.atlassian.net/browse/MC-1852)
People Involved   | 
Update CleverTap SDK dependency to 7.0.0
> Update CT to 7.0.0
