Leanplum/Leanplum-iOS-SDK

- Leanplum-SDK/Classes/Constants.h
- Leanplum-SDK/Classes/Constants.m
- Leanplum-SDK/Classes/Leanplum.h
As discussed w/ infrastructure team, we will need to point to api.leanplum.com enabling them to migrate some services in the future independently.
> refactor(api): change to api.leanplum.com

- Leanplum-SDK/Classes/LPActionManager.m
- Leanplum-SDK/Classes/LPInbox.m
- Leanplum-SDK/Classes/LPRegisterDevice.m
- Leanplum-SDK/Classes/Leanplum.m
- Leanplum-SDK/Classes/LeanplumRequest.h
- Leanplum-SDK/Classes/LeanplumRequest.m
There can be a corner case when the last response is not the response we are looking for. This is
highly unlikely because you need to have more than 10k events beforehand and need to have events
rights after you call start/forceContentUpdate, but this commit will fix it.
> Fix/remove getlastresponse/lp 4868

- Example/Tests/Classes/EventDataManagerTest.m
- Leanplum-SDK/Classes/LPNetworkOperation.m
If the server responds correctly but without a success code (200), it did not call the error
handler. This commit fixes this.
> fix(network): Handle http response from the server correctly

- Leanplum-SDK/Classes/Utils.m
This PR includes a change to enable using the SDK with Rubymotion:
- Condition to check for object count only if the object is not an NSString or subclass of NSString. The string size is checked in the length condition.
> fix(utils): Ruby string count check

- Leanplum-SDK/Classes/LeanplumSocket.m
Support `applyVars` endpoint which is used to preview variable changes on test devices.
This is similar to https://github.com/Leanplum/Leanplum-Android-SDK/pull/91 and relies on https://github.com/Leanplum/Leanplum/pull/209
> Add applyVars to dev websocket

- Leanplum-SDK/Classes/Leanplum.m
This patch only sets `LP_PARAM_DEVICE_NAME` if `[LPConstantsState sharedState].isDevelopmentModeEnabled` is true. If the SDK is not running in development mode, the device name defaults to an empty string.
> Only send device name in development mode

- Leanplum-SDK/Classes/Leanplum.m
https://leanplum.atlassian.net/browse/LP-6090
If there is a chained message to be delivered that is not yet present on the device, we will now `forceContentUpdate` and execute it once `forceContentUpdate` completes.
> fix: Fetch chained message via forceContentUpdate if it doesn't exist

- Leanplum-SDK/Classes/Constants.m
- Leanplum-SDK/Classes/LPCrashHandler.h
- Leanplum-SDK/Classes/LPCrashHandler.m
- Leanplum-SDK/Classes/Leanplum.m
- Leanplum-SDK/Classes/Utils.h
- Leanplum-SDK/Classes/Utils.m
The iOS SDK needs to report crashes. We will add another repo which will provide different crash reporting services to the main repo. This commit adds the interface for a general crash handler and looks specifically for a raygun provider
> Add crash monitoring handler

- Leanplum-SDK/Classes/LPActionArg-Internal.h
- Leanplum-SDK/Classes/LPActionArg.m
- Leanplum-SDK/Classes/LPActionContext-Internal.h
- Leanplum-SDK/Classes/LPActionContext.m
- Leanplum-SDK/Classes/LPActionManager.m
- Leanplum-SDK/Classes/LPVar-Internal.h
- Leanplum-SDK/Classes/LPVar.m
Read only properties don't need to be named "private_" since they cannot be changed anyway (would throw compiler error)
> Change naming convention to not include "private_" for readonly properties

- Leanplum-SDK/Classes/LPVar.m
obj-c - you can't call self.var inside the setVar block
> fix recursive call

- Example/Tests/Classes/LPMessageTemplatesClassTest.m
- Example/Tests/Classes/LPUtilsTest.m
- Leanplum-SDK/Classes/LPMessageTemplates.m
- Leanplum-SDK/Classes/Utilities/Utils.h
- Leanplum-SDK/Classes/Utilities/Utils.m
"LPMessageTemplates.h" is one of 4 publicly exposed files when we package the SDK. It needed a utility function that I previously added to Util.h. However, this is a helper method that is not used elsewhere so it can be moved directly into "LPMessageTemplates.h"
The reason to make this change is that we were referencing the "Util.h" file from "LPMessageTemplates.h" and this was breaking compilation, since "Util.h" is not publicly exposed
> LP-9384: move helper method to class file that uses it

- Example/Tests/Classes/LPMessageTemplatesClassTest.m
- Leanplum-SDK/Classes/Internal/LPInternalState.h
- Leanplum-SDK/Classes/Internal/LPInternalState.m
- Leanplum-SDK/Classes/Internal/Leanplum.m
- Leanplum-SDK/Classes/LPMessageTemplates.m
https://leanplum.atlassian.net/browse/E2-1492
sharedTemplates is using an anti-singleton-anti-pattern. It is a dependency in its own initialization path. This pattern will remain because I don't know the right way to initialize it elsewhere. I centralized the flag to mark it as initialized so any callers can't cause deadlock, which was happening.
> Fix deadlock initializing sharedTemplates

- Leanplum-SDK/Classes/Features/Variables/LPVarCache.m
Fixes #
Readded the line to instantiate the new messages diff directory. Avoid storing the previous cached values.
-
-
-
> Fix the mistaken deletion in cache

- Leanplum-SDK/Classes/LPMessageTemplates.m
Fixes #
This PR fixes following 4 issues:
All are specific to iPhone X correct?
1. iPhone X: Close button not showing up for "War Dragons game" .
2.iPhone X: Layout issues on top status bar on rich Interstitial .
3. iPhone X: Layout issues on right and left of the rich Interstitial cutting right and left view.
4. iPhone X: For Web interstatial, where we provide the close button.The button is cutting at the edge on landscape mode.
**Previous:**
**Fixed:**
**Previous:**
**Fixed:**
**Previous:**
**Fixed:**
-
-
-
> LP-9953: iPhone X Interstitial and Web Insterstitial layout fixes

- Leanplum-SDK.xcodeproj/project.pbxproj
- Leanplum-SDK.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Leanplum-SDK.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Leanplum-SDK.xcodeproj/xcshareddata/xcschemes/Leanplum-iOS-Example.xcscheme
- Leanplum-SDK.xcodeproj/xcshareddata/xcschemes/Leanplum-tvOS-Example.xcscheme
- Leanplum-SDK.xcodeproj/xcshareddata/xcschemes/LeanplumSDK-iOS.xcscheme
- Leanplum-SDK.xcodeproj/xcshareddata/xcschemes/LeanplumSDK-tvOS.xcscheme
- Leanplum-SDK/Classes/Internal/EnumConstants.h
- Leanplum-SDK/Classes/Managers/LPCountAggregator.h
- Leanplum-SDK/LeanplumSDK_iOS-Info.plist
- Leanplum-SDK/LeanplumSDK_iOS.h
- Leanplum-SDK/LeanplumSDK_tvOS-Info.plist
- Leanplum-SDK/LeanplumSDK_tvOS.h
- Podfile
Fixes #239 
This PR simply adds a new Xcode project file to the repository. This project file is configured with 2 framework targets for the Leanplum SDK - one for iOS and one for tvOS.
I've also included 2 targets the "Example" apps that are part of the repository but as far as I can see they are just placeholders that have never really been used as integration examples.
I'd have done a much bigger clean up but I left it out in the interest of keeping this PR small and to the point.
-
-
-
> Adds support for building the Leanplum SDK via Carthage

- .travis.yml
- Tools/verifyTag.sh
When deploying, we want the build machine to fail if the tag and the sdk-version.txt files are out of sync
> Verify tag during deploy

- Leanplum-SDK/Classes/Features/Actions/LPActionManager.h
- Leanplum-SDK/Classes/Features/Actions/LPUIAlert.h
Objective-C header warnings are not inhibited when integrating through CocoaPods into a Swift project, so I had to add this to silence them.
> Silences deprecation warnings in header files

- Leanplum-iOS-SDK.podspec
We removed the TV OS parts of our code, since we weren't supporting that platform. However, it needs to also be removed from the Podspec, else the pod lint fails.
> remove tvos deployment target

- Example/Podfile
- Leanplum-iOS-SDK.podspec
For Carthage, our built framework needs to include bitcode. To enable this, we put the flags in the podspec. However, this forced everyone to use bitcode for all their pods, and became a problem for some customers. By moving the needed flags into the Podfile of our example, we still get the bitcode during compilation, but it is not forced by the Podspec on everyone.
https://leanplum.atlassian.net/browse/E2-1825
> move bitcode flags to podfile from podspec

- Example/Leanplum-SDK.xcodeproj/project.pbxproj
- Example/Tests/Classes/LPActionContextTest.m
- Leanplum-SDK/Classes/Features/Actions/LPActionContext.m
Currently when a message is shown on an app (the message is active and not closed), and the message is removed (or paused) on the dashboard, the message args become nil on the app when the user returns, causing UI issues and interaction issues. 
This fix prevents args from being set to nil when a message is present on an app but removed on the dashboard.
reference: https://leanplum.atlassian.net/browse/LP-10296
> LP-10296 fix: iOS banner expand to fullscreen and unresponsive

- Leanplum-SDK.xcodeproj/project.pbxproj
Fixes #
Project currently doesn't build and therefore doesn't support Carthage unless you're using the pre-compiled binary attached to the GitHub release.
> Remove missing source files from compile source build phase

- Leanplum-SDK/Classes/Internal/Leanplum.m
JIRA Issue        | [LP-10616](https://leanplum.atlassian.net/browse/LP-10616)
People Involved   | @aafrooze @e7mac @gg4race 
Multiple crashes were reported. All revolving around NSNotification. The suspect for these are the notification observers not being released.
Block based observers via the -[NSNotificationCenter addObserverForName:object:queue:usingBlock] method still need to be un-registered when no longer in use since the system still holds a strong reference to these observers.
Its not possible to test these, since logging is not supported for deallocation block of memory or delegates.
> fix crash due to observers with blocks not being released.

- Leanplum-SDK/Classes/Features/Actions/LPActionManager.h
- Leanplum-SDK/Classes/Leanplum.h
JIRA Issue        | n/a
People Involved   | Only me
Compiler warnings continue to pop up in our logs.
Deprecation warnings are now ignored using `clang diagnostic`
N/A
Yes.
> Removed compiler warnings

- Leanplum-SDK/Classes/Features/Actions/LPActionManager.m
JIRA Issue        | [LP-10840](https://leanplum.atlassian.net/browse/LP-10840)
People Involved   | @milos1290 @aafrooze @gg4race @e7mac 
P2 Crash due to missing check for local notification.
I have manually tested using RondoQA app. And will be adding the test to release rule book.
Run the RondoQA all with this code. And check if all notifications are received and then click on the notifications.
> Lp 10840 crash local

- Example/Tests/Classes/LPActionManagerTest.m
- Leanplum-SDK/Classes/Features/Actions/LPActionManager.m
JIRA Issue        | [E2-2047](https://leanplum.atlassian.net/browse/E2-2047)
People Involved   | @shivanshukumar , @hrishileanplum 
The gist of the problem is that the "description" method of NSData began returning different result in iOS 13 Beta 2 and newer. Many SDKs use this method to get the push token, but now it will no longer return the full push token.
I see that the Leanplum iOS SDK is affected based on the code here: https://github.com/Leanplum/Leanplum-iOS-SDK/blob/dd9f404aa07f479978289a5543a213d88700262c/Leanplum-SDK/Classes/Features/Actions/LPActionManager.m#L755 …
> E2-2047: update method to get push token for iOS 13

- Leanplum-SDK/Classes/LPMessageTemplates.m
JIRA Issue        | [LP-11035](https://leanplum.atlassian.net/browse/LP-11035)
If you have a ASK based 2 button prompt displayed, the cancel button state was used for the subsequent popup layout displays. So, if there was a UI which was "push_Ask" false, without a cancel button. It still used the previous cancebutton value as a check, which was incorrect.
Get the latest data and not relay on incorrect previous state cached value.
> Fix the old cached data based check

- Leanplum-SDK/Classes/Notifications/Push/LPPushNotificationsHandler.m
JIRA Issue        | [LP-11331](https://leanplum.atlassian.net/browse/LP-11331)
People Involved   | 
[LP-11331](https://leanplum.atlassian.net/browse/LP-11331)
When the UNUserNotificationCenter delegate is used, the application is already in Active state when the `LPActionManager:didReceiveRemoteNotification` is called. This results in not handling the notification open action although it was received when the app was not on foreground (active).
Change the conditions so they do not prevent further handling the notification. This is based on the flow of handling the notification described below.
App is foreground
`willPresentNotification -> handleWillPresentNotification`
After that …
> [LP-11331] Fix Open action when Mute Inside App is used

- Leanplum-SDK/Classes/Leanplum.h
Two arguments in the `+ (void)startWithUserId:userAttributes:responseHandler:)` method are incorrectly annotated as `nonnull` (owing to `NS_ASSUME_NONNULL_BEGIN`) when they should be `nullable`.
This results in the following error in the following code in `Leanplum.m:348 :
> Null passed to a callee that requires a non-null argument
``` objective-c
+ (void)start
{
[self startWithUserId:nil userAttributes:nil responseHandler:nil];
}
```
I have annotated the relevant arguments with `nullable` to silence this warning and more accurately reflect the fact that the method can accept `nil` arguments.
N/A
Yes, making non null arguments nullable does not cause backwards compatibility issues, the reverse is not necessarily true.
> Fix Nullability Annotation Warnings

- Leanplum-SDK/Classes/Utilities/LPDatabase.m
Since NSUInteger is variable size based on architecture, it’s best to cast the variable to an explictly sized unsigned long and use the appropriate format specifier
N/A
N/A
Yes
> Fix Integer Format Specifier Warning

- Leanplum-SDK/Classes/Managers/LPRevenueManager.m
`SKPaymentTransaction.transactionReceipt` is marked as unavailable on Mac Catalyst, in favor of `NSBundle.mainBundle.appStoreReceiptURL`. This PR compiles out the old API when building for Catalyst.
N/A
N/A
Yes
> Fix Catalyst Build Error

- Leanplum-SDK/Classes/Notifications/Push/LPPushNotificationsHandler.m
prevent tracking open for remote notifications when app is in foreground and there is no users action
JIRA Issue        | [LP-11379](https://leanplum.atlassian.net/browse/LP-11379)
> prevent tracking open for remote notifications when app is active

- Example/Tests/Classes/LPInboxTest.m
- Example/Tests/Classes/Utilities/LeanplumHelper.m
- Leanplum-SDK/Classes/Features/Inbox/LPInbox.m
- Leanplum-SDK/Classes/LPInbox.h
JIRA Issue        | [LP-11409](https://leanplum.atlassian.net/browse/LP-11409)
Add an option to mark an inbox message as read without running the message open action.
Move the logic for marking a message as read and sending a request to a separate method.
Added separate unit tests for both `read` and `markAsRead` methods of `LPInbox`.
Yes
> [LP-11409] Add method to mark Inbox message as read

- Leanplum-SDK/Classes/MessageTemplates/LPPushAskToAskMessageTemplate.h
- Leanplum-SDK/Classes/MessageTemplates/LPPushAskToAskMessageTemplate.m
- Leanplum-SDK/Classes/MessageTemplates/LPPushMessageTemplate.h
- Leanplum-SDK/Classes/MessageTemplates/LPPushMessageTemplate.m
- Leanplum-SDK/Classes/MessageTemplates/LPRegisterForPushMessageTemplate.h
- Leanplum-SDK/Classes/MessageTemplates/LPRegisterForPushMessageTemplate.m
JIRA Issue        | [SDK-41](https://leanplum.atlassian.net/browse/SDK-41)
View events are tracked for Register for Push action even if the prompt is not shown.
Combine the logic for checking and calling the native prompt under an LPPushMessageTemplate. AskToAsk and RegisterForPush inherit from that one.
Yes
> [SDK-41] register for push

- Example/Tests/Classes/LeanplumTest.m
- Leanplum-SDK/Classes/Internal/Leanplum.m
JIRA Issue        | [SDK-114](https://leanplum.atlassian.net/browse/SDK-114)
Perform actions (display in-app messages) on start even if the start fails.
> Perform actions after start error

- Example/Tests/Classes/Extensions/LPRequestSender+Categories.h
- Example/Tests/Classes/Extensions/LPRequestSender+Categories.m
- Example/Tests/Classes/Extensions/Leanplum+Extensions.h
- Example/Tests/Classes/LPCountAggregatorTest.m
- Example/Tests/Classes/LeanplumTest.m
- Leanplum-SDK/Classes/Internal/LPInternalState.h
- Leanplum-SDK/Classes/Internal/LPInternalState.m
- Leanplum-SDK/Classes/Internal/Leanplum.m
- Leanplum-SDK/Classes/Leanplum.h
- Leanplum-SDK/Classes/Managers/LPLogManager.m
- Leanplum-SDK/Classes/Managers/Networking/LPFileTransferManager.m
- Leanplum-SDK/Classes/Managers/Networking/LPRequestSender.h
- Leanplum-SDK/Classes/Managers/Networking/LPRequestSender.m
- Leanplum-SDK/Classes/MessageTemplates/LPCenterPopupMessageTemplate.m
- Leanplum-SDK/Classes/MessageTemplates/LPPushAskToAskMessageTemplate.m
- Leanplum-SDK/Classes/MessageTemplates/ViewControllers/LPPopupViewController.h
- Leanplum-SDK/Classes/MessageTemplates/ViewControllers/LPPopupViewController.m
- Leanplum-SDK/Classes/Notifications/Push/LPPushNotificationsHandler.h
- Leanplum-SDK/Classes/Notifications/Push/LPPushNotificationsHandler.m
- Leanplum-SDK/Classes/Utilities/LPUtils.h
- Leanplum-SDK/Classes/Utilities/LPUtils.m
JIRA Issue        | [SDK-125](https://leanplum.atlassian.net/browse/SDK-125)
JIRA Issue        | [SDK-88](https://leanplum.atlassian.net/browse/SDK-88)
Enable reuse of the Center Popup message template for Ads Pre-permission message.
Enable switching device ids after Leanplum has started.
1. Refactor the Center Popup message template to be more generic
2. Introduce `setDeviceIdInternal` method similar to the `setUserIdInternal`, to set a device id and 'switch' to this device.
The APIConfig deviceId should be updated as well as the VarCache, so the device id is persisted.
The device attributes must be updated to reflect the current device information.
Introduced common appVersion logic to reuse the …
> Switch device ID and Ads pre-permission

- Leanplum-SDK.xcodeproj/project.pbxproj
The file was added to the `Leanplum.h` header file but was not made public, so apps got errors when importing the SDK.
In #391 the `#import LPLogManager.h` was added to `Leanplum.h`, the framework umbrella header. They file was private until then, so it was not copied to the framework headers directory. When imported the SDK, the compiler complained that the `LPLogManager.h` doesn't exist.
Yes
The example app didn't compile locally because of this issue.
> add missing file to framework public headers.

- Leanplum-SDK/Classes/Internal/Leanplum.m
- Leanplum-SDK/Classes/Leanplum.h
Fix for `AST Deserialization Issue`:
` 'Leanplum' defined here has different definitions in different modules; first difference is this method`
> Fix Xcode 12 different definitions

- Leanplum-SDK/Classes/Leanplum.h
The macro does not work on iOS 14. Removing it to prevent customer's confusion.
Documentation will be added on how customers can set the IDFA now.
> Remove IDFA macro

- Leanplum-SDK.xcodeproj/project.pbxproj
This commit adds missing files from the project. Without this change if
you build the framework from source using Xcode and without Cocoapods,
the build fails.
> Add missing files to project.

- Leanplum-SDK/Classes/Notifications/Local/LPLocalNotificationsManager.m
JIRA Issue        | [SDK-279](https://leanplum.atlassian.net/browse/SDK-279)
Local Notification is not cancelled when the Unless condition is triggered.
Remove the pending notification that is scheduled to be sent.
> [SDK-279] Fix cancel local notification

- Leanplum-SDK/Classes/MessageTemplates/ViewControllers/LPWebInterstitialViewController.m
- Leanplum-SDK/Classes/MessageTemplates/Views/LPHitView.h
- Leanplum-SDK/Classes/MessageTemplates/Views/LPHitView.m
JIRA Issue        | [SDK-172](https://leanplum.atlassian.net/browse/SDK-172)
There seems to be an issue with  Banner closing when the Tap Outside to Close option is enabled.
The problem was that tap (touch) was forwarded to the view of the presenter view controller.
Intercept forwarding the tap (touch) to the view of the presenter when the tap to close option is set to true. So with any touch outside of the banner we can close it.
> Banner tap outside to close fix

- Leanplum-SDK/Classes/Features/Variables/LPVarCache.m
Prevent error when loading variable diffs from VarCache for ActionDefinitions that have an Array ActionArg.
Example error:
`[LEANPLUM] [ERROR]: Could not load variable diffs: -[__NSCFNumber length]: unrecognized selector sent to instance`
Check the type of the diffs before trying to merge them with the default array value.
> Fix loading of array args from cache

- Leanplum-SDK/Classes/Managers/Networking/LPRequest.m
- Leanplum-SDK/Classes/Managers/Networking/LPRequestSender.m
JIRA Issue        | [SDK-337](https://leanplum.atlassian.net/browse/SDK-337)
The SDK was throwing crash when trying to save request within operation block on background thread but the operation was somehow canceled (dealloc) before executing the block.
Before executing the operation check if it is canceled.
Yes
> Fix NSBlockOperation dealloc crash

- Example/Tests/Classes/LPPushNotificationsManagerTest.m
- Leanplum-SDK/Classes/Notifications/Push/LPPushNotificationsHandler.m
JIRA Issue        | [SDK-361](https://leanplum.atlassian.net/browse/SDK-361)
Ensure Leanplum has started when sending push token and settings. This prevents making requests before userId and deviceId are set/loaded.
Wrap the `send request` code in a `onStartResponse` block.
Added new unit test.
> [SDK-361] Send push token and settings after Leanplum start

- Example/Tests/Classes/LPPushNotificationsHandlerTest.m
- Leanplum-SDK/Classes/Notifications/Push/LPPushNotificationsHandler.m
JIRA Issue        | [SDK-274](https://leanplum.atlassian.net/browse/SDK-274)
Notification Open Action not working on iOS 13 when App is running in the background and the notification is opened from locked screen.
1) Remove the `UIApplicationState` check.
2) Add `isDuplicateNotification:userInfo` check. This prevents showing in-app confirm message for the Push (the one we show when a notification arrives while the app is in foreground) when it was opened. 
This was side effect from step 1. The notification open action was executed correctly but when returning to the app, this confirm was also shown.
Manual Testing on iOS 14 and iOS 13 using Rondo iOS.
Locked | App State | Success
-- | -- | --
N/A | …
> [SDK-274] Fix open notification

- Leanplum-SDK/Classes/Utilities/LPDatabase.m
JIRA Issue        | [SDK-398](https://leanplum.atlassian.net/browse/SDK-398)
was crashing sqlite connections from other libs/frameworks
> removing sqlite config

- LeanplumSDK/LeanplumSDK/Classes/Internal/LPConstants.h
- LeanplumSDK/LeanplumSDK/Classes/Internal/LPConstants.m
- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/Classes/Leanplum.h
- LeanplumSDKApp/LeanplumSDKTests/Classes/Utilities/LeanplumHelper.m
`setVerboseLoggingInDevelopmentMode` is obsolete, use `[Leanplum setLogLevel:Debug];` instead.
The method is already removed from the Android SDK.
Remove the method and the associated property. Use Debug Log level `[Leanplum setLogLevel:Debug];`
> Remove verbose logging

- LeanplumSDK/LeanplumSDK/Classes/Internal/LPConstants.h
- LeanplumSDK/LeanplumSDK/Classes/Internal/LPConstants.m
- LeanplumSDK/LeanplumSDK/Classes/Internal/LPInternalState.h
- LeanplumSDK/LeanplumSDK/Classes/Internal/LPInternalState.m
- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/Classes/Leanplum.h
- LeanplumSDK/LeanplumSDK/Classes/Notifications/Push/LPPushNotificationsHandler.m
Remove dead code:
- `setFileHashingEnabledInDevelopmentMode` (uses old network layer)
- `checkForUpdatesInDevelopmentMode` (used by setFileHashingEnabledInDevelopmentMode)
- `setNetworkActivityIndicatorEnabled` (uses old network layer)
- `stripViewControllerFromState` (used with the deprecated UIEditor)
- `trackAllAppScreens` (only works with the deprecated UIEditor)
- `trackAllAppScreensWithMode` (only works with the deprecated UIEditor)
- `LPTrackScreenMode` (only works with the deprecated UIEditor)
Unnecessary check:
- `canDownloadContentMidSessionInProduction` - apply diffs in production when `getVars` is called to fetch new data. All data is already returned by the server (the `includeMessage` param does not change this behavior).
Deprecated:
- `enableTestMode` (use `setTestMode:` …
> Remove dead code

- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/Classes/LPVar.h
- LeanplumSDK/LeanplumSDK/Classes/Leanplum.h
JIRA Issue        | [SDK-577](https://leanplum.atlassian.net/browse/SDK-577)
Adds a success flag that indicates whether the getVars API request was successful or not.
Add a new method since the current one cannot be overloaded with a different block.
Yes
> ForceContentUpdate with boolean flag

- LeanplumSDKApp/LeanplumSDKTests/Classes/LeanplumNotificationsManagerTest.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/LeanplumPushNotificationsProxyTest.swift
Unit Tests Swift compilation compatibility with Xcode 12.
The same code compiles successfully on Xcode 13.
Addresses CompileSwift errors.
`Abort trap: 6 Command CompileSwift failed with a nonzero exit code`
The compilation will fail on Xcode 12 if a variable with the same name is already defined and that same name is used in `guard let` statement (`if let` works). Example:
```
let a = ""
var b:Bool?
guard let a = b else {
return
}
```
The above style is also confusing, so this PR fixes it.
`UNNotificationResponseTestCoder` tried to call abstract `decodeInt64ForKey` for `actionOptions` key. Implementing the method and ignoring that key.
Tested with Xcode 12.0
Yes
> Xcode 12 compatibility

- LeanplumSDK/LeanplumSDK/Classes/Managers/LPLogManager.h
- LeanplumSDK/LeanplumSDK/Classes/Managers/LPLogManager.m
- LeanplumSDKApp/LeanplumSDKTests/Classes/Utilities/LeanplumHelper.m
Renamed the LPLogLevel enum cases to be prefixed with `LPLogLevel`.  This helps avoid conflicts with other SDKs that define the same enum names globally.
- Renamed LPLogLevel cases to have the `LPLogLevel` prefix
- Updated usage within the SDK and tests
We would like to update the latest SDK without having to use a forked version.  Currently the LPLogLevel enums collide with another 3rd party SDK that we don't have the ability to change.
Prefixed …
> Rename LPLogLevel enum cases

- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumNotificationSettings.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumNotificationsManager+Utils.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumNotificationsManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumPushNotificationsProxy.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumUtils.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/NSObject+Notifications.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/UNNotificationSettings+LPUtil.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/LeanplumNotificationsManagerTest.swift
Structural changes
Reorganize the methods inside the classes, add marks for easier navigation.
Move some utils method from `LeanplumUtils` to `LeanplumNotificationsManager+Utils` extension
Yes
> Improve Notification classes structure

- LeanplumSDK/LeanplumSDK/Classes/Features/Actions/LPActionManager.m
- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/Classes/Notifications/Local/LPLocalNotificationsManager.h
- LeanplumSDK/LeanplumSDK/Classes/Notifications/Local/LPLocalNotificationsManager.m
JIRA Issue        | [SDK-595](https://leanplum.atlassian.net/browse/SDK-595)
Move away from using `onAction` and `triggerAction` for Local Notifications schedule and cancel.
> Do not use OnAction for Local Notifications

- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/Classes/Leanplum.h
- LeanplumSDK/LeanplumSDK/Classes/Utilities/LPSwizzle.m
- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumNotificationsManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumPushNotificationsProxy.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/NSObject+Notifications.swift
Remove `isIOSVersionGreaterThanOrEqual` function used for testing.
Improve log messages.
> Remove iOS version check func

- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/Classes/Leanplum.h
- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumNotificationsManager+Utils.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumNotificationsManager.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/LeanplumPushNotificationSettingsTest.swift
JIRA Issue        | 
Having option to enable push notifications and provisional push through the SDK
Adding methods in Leanplum class that will call corresponding methods from notificationManager
> Expose push enable methods

- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/Classes/Leanplum.h
- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumNotificationSettings.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumNotificationsManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/LeanplumPushNotificationsProxy.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/NSObject+Notifications.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/UIUserNotificationSettings+LPUtil.swift
JIRA Issue        | [SDK-609](https://leanplum.atlassian.net/browse/SDK-609)
Completion handlers should be executed by the client's app if Swizzling is Disabled.
Fix push types and categories for iOS 9
Improve custom push actions actionName (hence event name also).
Remove the handlers from the parameters of the methods.
> Completion handlers improvements

- LeanplumSDK/LeanplumSDK.xcodeproj/project.pbxproj
- LeanplumSDK/LeanplumSDKBundle/Supporting Files/Info.plist
JIRA Issue        | [SDK-660](https://leanplum.atlassian.net/browse/SDK-660)
Our Leanplum bundle has executable inside and is making problems in the clients app, it's not passing AppStore validation.
This executable is actually not needed, because it does not contain anything, so the solution is to remove `CFBundleExecutable` key from bundle's Info.plist and to remove `Compile Sources` and `Link Binary with Libraries` from bundle's Build Phases.
testing with SPM to see if the AppStore validation will pass.
Yes
> fix bundle structure to not create executable

- LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/ViewControllers/LPWebInterstitialViewController.h
- LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/ViewControllers/LPWebInterstitialViewController.m
JIRA Issue        | [SDK-640](https://leanplum.atlassian.net/browse/SDK-640)
By default WKWebView does not support `target="_blank"` so urls with this target were not handled
solution  is to cancel the navigation and load the request with loadRequest: again. This will have the similar behaviour like UIWebView which always open new window in the current frame.
[reference link](https://stackoverflow.com/a/25853806)
Manual testing by sending WebInterstitial with page that has `target="_blank"` url
Yes
> add support in WKWebView for urls with target="_blank"

- LeanplumSDKLocation/LeanplumSDKLocation/Classes/LPLocationManager.m
JIRA Issue        | [SDK-641](https://leanplum.atlassian.net/browse/SDK-641)
When using our Location SDK by default we had set to `requestAlwaysAuthorization` which was leading to ask for information in Info.plist meaning to add `NSLocationAlwaysAndWhenInUseUsageDescription` and for the users that were only using `NSLocationWhenInUseUsageDescription` this is not acceptable.
Lower the level of authorization to when in use by asking for `requestWhenInUseAuthorization` which means that only by adding `NSLocationWhenInUseUsageDescription` in Info.plist app …
> Use  requestWhenInUseAuthorization instead of requestAlwaysAuthorization

- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager.swift
Make ActionManager callbacks optional. This way the handler closures can be removed by setting to nil.
The underlying implementation already uses optional closures.
Optional function parameters are `@escaping` by default
> ActionManager callbacks optional

- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/Classes/Leanplum.h
- LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/LPAppRatingMessageTemplate.m
- LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/LPOpenUrlMessageTemplate.m
- LeanplumSDK/LeanplumSDK/Classes/Utilities/LPUtils.h
- LeanplumSDK/LeanplumSDK/Classes/Utilities/LPUtils.m
- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager+Definition.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager+Executor.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager+Tracking.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Actions/ActionManager.swift
> Action manager fixes

- Tools/build.sh
Issue        | #495 
Remove module name from xcframework swiftinterface.
The same is already done for dynamic xcframework.
Update the simulator destination to more specific one.
> Remove module name from xcframework swiftinterface

- .travis.yml
- LeanplumSDKApp/LeanplumSDKApp.xcodeproj/project.pbxproj
- LeanplumSDKApp/LeanplumSDKApp/Supporting Files/Info.plist
- LeanplumSDKApp/LeanplumSDKTests/Classes/LPWebInterstitialViewControllerTest.m
- LeanplumSDKLocation/LeanplumSDKLocation.xcodeproj/project.pbxproj
- LeanplumSDKLocation/LeanplumSDKLocation/Classes/LPLocationManager.m
Adding a dependency from another project where there are multiple targets that produce the same product, results in the following warning:
```
Multiple targets match implicit dependency for product reference 'Leanplum.framework'. Consider adding an explicit dependency on the intended target to resolve this ambiguity.
```
In the above case, both `Leanplum` and `Leanplum-Static` produce the same product - `Leanplum.framework`. Unfortunately, even if you choose the desired target from the list, there is no guarantee that Xcode will build that product. In this case, the dependency is implicit, hence the above warning.
The main problem is that this can result in mixing …
> Use explicit dependencies

- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/CTWrapper+Utilities.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/CTWrapper.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/Migration/CTWrapperTest.swift
1) CleverTap needs to track AppLaunched in order to track other events when initialized mid-session. This addresses the following error:
`App Launched not yet processed re-queueing`
2) Fix transforming array values if such contains `nil`. Remove the `nil` values and ensure the other elements are unwrapped.
1) Add `cleverTapInstance?.notifyApplicationLaunched(withOptions: [:])` once the instance is created
2) Cast the array to `Any?`, remove nil values, then create a String by force-unwrapping them.
3) Rename `transformAttributeValues` to `transformArrayValues`
Manual + new Test cases
> Migration: fix AppLaunched and transform array values

- LeanplumSDK/LeanplumSDK/Classes/Managers/Networking/LPRequestSender.m
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/CTWrapper.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/Extensions/Leanplum+Extensions.h
- LeanplumSDKApp/LeanplumSDKTests/Classes/Migration/CTWrapperTest.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/Migration/Migration+Extensions.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/Utilities/LeanplumHelper.m
Use `pushInstallReferrerSource` to set traffic source info.
- Use `pushInstallReferrerSource` instead of tracking event.
- Fix test warnings.
- Remove commented-out code in the sender.
> Use pushInstallReferrerSource

- LeanplumSDK/LeanplumSDK.xcodeproj/project.pbxproj
- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/LPCTNotificationsManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager+API.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/CTWrapper.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/Wrapper.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Notifications/NSObject+Notifications.swift
JIRA Issue        | [SDK-2316](https://wizrocket.atlassian.net/browse/SDK-2316)
Support Notifications from both Leanplum and CleverTap
CT swizzling is not called (no swizzling of iOS delegate methods) when using a custom instance and the method is internal.
Instead of using double swizzling, check if the notification comes from Leanplum and if not, forward it to CleverTap to handle it using the `CleverTap.handlePushNotification` method.
Create a new `NotificationsManager` that inherits from it and handles both CT and LP notifications. Override the push `receive` and `open` methods. Call the corresponding SDK based on the push payload. Handle registration with a device …
> CT Push Migration

- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
`UIApplicationWillEnterForegroundNotification` is called when app is started and enters foreground.
Add a check if Leanplum has started, to prevent calling resume right after start.
> Fix resume called on app start

- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/CTWrapper.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/IdentityManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Utilities/Utilities.swift
- LeanplumSDKApp/LeanplumSDKApp.xcodeproj/project.pbxproj
- LeanplumSDKApp/LeanplumSDKTests/Classes/Migration/IdentityManagerTest.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/UtilitiesTest.swift
- Podfile
JIRA Issue        | [SDK-2352](https://wizrocket.atlassian.net/browse/SDK-2352)
The CTID generated until now, could contain invalid symbols or exceed the designated length.
Current format:
* anonymous `<CTID=deviceId, Identity=null>`
* non-anonymous `<CTID=deviceId_userId, Identity=userId>`
New format:
* anonymous `<CTID=deviceId, Identity=null>`
* non-anonymous `<CTID=deviceId_userIdHash, Identity=userId>`
* if invalid deviceId `deviceId=deviceIdHash`
The userId Hash is generated using the first 10 chars of the userId SHA256 string (hex).
If the deviceId does _not_ pass validation _or_ is _longer_ than 50 characters, we use the first 32 chars of the deviceId SHA256 …
> Validate and Hash CTID

- Leanplum-iOS-SDK.podspec
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/CTWrapper.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/IdentityManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Utilities/Utilities.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/Migration/IdentityManagerTest.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/UtilitiesTest.swift
- Change deviceId hash length to 50, to minimize collisions for anonymous users.
- Rename `devices` user property to `lp_devices`
- Set `lp_device` for anonymous users, so merging multiple anonymous users does not override `lp_devices`
- Use `lp_devices` for non-anonymous users only
> Change device id hash length

- LeanplumSDK/LeanplumSDK/Classes/MessageTemplates/ViewControllers/LPWebInterstitialViewController.m
The Banner in-app message was not dismissed properly.
Dismiss the controller - parent view controller and subview are no longer used.
Manual
Yes
> Fix banner dismiss

- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
JIRA | [SDK-2386](https://wizrocket.atlassian.net/browse/SDK-2386)
`UIApplicationWillEnterForegroundNotification` calls the block when the app is starting (immediately after `didFinishLaunchingWithOptions`). This results in executing `maybePerformActions` for `resume` before the application has started, showing an in-app unintended.
Execute `resume` logic only if Leanplum has already `started`. Resuming the application before calling Leanplum `start` will be a NOP.
> Prevent resume actions on app start

- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager+API.swift
Public read-only access to the CleverTap migration config.
This way PropertyWrappers can be kept internal as well.
> Migration config public getters

- Leanplum-iOS-SDK.podspec
- Package.swift
- Podfile
JIRA Issue        | [SDK-2535](https://wizrocket.atlassian.net/browse/SDK-2535)
Update CleverTap SDK to 4.2.0, so SDWebImage dependency can be updated.
Issue #549
> Bump CleverTap SDK version

- LeanplumSDK/LeanplumSDK.xcodeproj/project.pbxproj
- LeanplumSDKApp/LeanplumSDKApp.xcodeproj/project.pbxproj
- LeanplumSDKLocation/LeanplumSDKLocation.xcodeproj/project.pbxproj
- Podfile
- Tools/build.sh
JIRA Issue        | [SDK-2616](https://wizrocket.atlassian.net/browse/SDK-2616)
Leanplum dynamic framework was an umbrella framework and embedded its dependency - CleverTapSDK and its dependencies, in the nested Frameworks folder. This was previously discouraged by Apple but now causes the AppStore Validation to fail with the following errors:
`"Invalid Bundle. The bundle at 'MyApp.app/Frameworks/Leanplum.framework' contains disallowed file 'Frameworks'".`
`"Invalid Bundle. The bundle at 'MyApp.app/Frameworks/Leanplum.framework' contains disallowed nested bundles".`
- LeanplumSDK - Do not embed the dependency frameworks. Remove the script that copied them.
- …
> Do not use dynamic umbrella framework

- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager+API.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager+Constants.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager+ResponseHandler.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/CTWrapper.swift
- LeanplumSDKApp/LeanplumSDKApp.xcodeproj/project.pbxproj
- LeanplumSDKApp/LeanplumSDKTests/Classes/Migration/CTWrapperTest.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/Migration/MigrationResponsesTest.swift
- LeanplumSDKApp/LeanplumSDKTests/Resources/Responses/get_migrate_state_response.json
- LeanplumSDKApp/LeanplumSDKTests/Resources/Responses/get_migrate_state_response_error.json
- LeanplumSDKApp/LeanplumSDKTests/Resources/Responses/get_migrate_state_response_missing.json
JIRA Issue        | [SDK-2684](https://wizrocket.atlassian.net/browse/SDK-2684)
Identity keys are received through `getMigrateState` and set in the CleverTap configuration.
Example JSON:
```
{
"ct" : {
"accountId" : "accId",
"attributeMappings" : ...,
"identityKeys" : ["Identity", "Phone", "Email"]
};
...
}
```
The default value is `"Identity"`.
If the keys are missing in the API response, or they are an empty array, they will not be updated. This means that previously saved or default keys will be used.
The keys that come from the API will not be further validated and will be passed directly as-is to the CT Config.
- Add the `identityKeys` to the `MigrationManager`
- …
> Implement migration identity keys

- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/Classes/Leanplum.h
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/LPCTNotificationsManager.swift
JIRA Issue        | [SDK-2966](https://wizrocket.atlassian.net/browse/SDK-2966)
Expose logic for CleverTap push notifications, so the behavior can be customized by clients using the Wrapper.
Changes default value for `openDeepLinksInForeground` to `false`.
Adds the following methods for better control over CleverTap push notifications:
- `setCleverTapOpenDeepLinksInForeground`
- `setHandleCleverTapNotification`
Manual
Yes
> Expose functionality for CleverTap push notifications

- LeanplumSDK/LeanplumSDK/Classes/Internal/Leanplum.m
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/LPCTNotificationsManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Notifications/Proxy/NotificationsProxy+Utilities.swift
JIRA Issue        | [SDK-3124](https://wizrocket.atlassian.net/browse/SDK-3124)
- Fix `isEqualToHandledNotification` for CleverTap notifications.
If the app is launched from a CleverTap push notification, the consequent CleverTap notification opens will not work since `isEqualToHandledNotification` always returns `true` for CleverTap notifications - for notifications without notification Id (`lp_occurrence_id` key).
- Default CleverTap `openDeepLinksInForeground` to `true` when called from `notificationOpened`, unless `openDeepLinksInForeground` is explicitly set. Fixes an issue on Unity when the application is opened from a notification and the app takes a while to …
> CleverTap Push fixes

- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager+Constants.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager+ResponseHandler.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/CTWrapper.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/IdentityManager.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/Migration/CTWrapperTest.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/Migration/IdentityManagerMocks.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/Migration/IdentityManagerTest.swift
- LeanplumSDKApp/LeanplumSDKTests/Classes/Migration/MigrationResponsesTest.swift
Use `loggedInUserId` to identify previously logged-in users and identify them on reinstall. Used for CleverTap Migration and CleverTap ID.
- Manual
- IdentityManager unit tests
Yes
> Migration: Use loggedInUserId to identify previously logged-in users

- LeanplumSDK/LeanplumSDK.xcodeproj/project.pbxproj
- LeanplumSDK/LeanplumSDK/Classes/Utilities/Vendor/WebSocket/Leanplum_WebSocket+Utils.h
- LeanplumSDK/LeanplumSDK/Classes/Utilities/Vendor/WebSocket/Leanplum_WebSocket+Utils.m
- LeanplumSDK/LeanplumSDK/Classes/Utilities/Vendor/WebSocket/Leanplum_WebSocket.m
- LeanplumSDKApp/LeanplumSDKApp.xcodeproj/project.pbxproj
- LeanplumSDKApp/LeanplumSDKTests/Classes/Leanplum_WebSocketTest.m
The socket connection to the DevServer started failing. The server error is `websocket connection invalid` which results in error `WebSocketErrorDomain error 2` in the SDK.
The errors are caused by changes/rewriting to the request headers and the response.
1. The server expects `Upgrade: WebSocket` but receives `Upgrade: websocket` (The SDK does send `Upgrade: WebSocket`). This is fixed on the server.
2. The SDK expects a specific response and headers (direct comparison) but receives:
```
HTTP/1.1 101 Switching Protocols
WebSocket-Origin: http://dev-staging.leanplum.com/
WebSocket-Location: ws://dev-staging.leanplum.com/socket.io/1/websocket/DDeRoYTza-zUWMyDHIio
Date: …
```
> DevServer connection fix - Improve sockets handshake response check

- LeanplumSDK/LeanplumSDK.xcodeproj/project.pbxproj
- LeanplumSDK/LeanplumSDK/Supporting Files/Info.plist
JIRA Issue        | [MC-1537](https://wizrocket.atlassian.net/browse/MC-1537)
SPM Compatibility with Xcode 15.3.
Addressing:
- Asset validation failed (90208) Invalid Bundle. The bundle does not support the minimum OS Version specified in the Info.plist.
- Asset validation failed. Invalid Bundle. The bundle at '' contains disallowed file 'Frameworks'.
- Workaround the Minimum OS Version by setting it to 100.0
- Remove the Copy Headers phase
Manual using local package.
Yes
> Xcode15.3 compatibility

- Leanplum-iOS-Location.podspec
- Leanplum-iOS-LocationAndBeacons.podspec
Move the xcprivacy file into resource bundle for Cocoapods. This prevents the error "multiple commands trying to produce xcprivacy file" when static linking is used.
> Move xcprivacy to Location pods bundle

- Package.swift
Update CleverTap SDK version. 
Update the version in SPM. 
CocoaPods uses 6.2 dependency which will automatically install 6.2.1.
> Update CleverTap SDK version

- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/LPCTNotificationsManager.swift
JIRA Issue        | [JIRA_TICKET_ID](https://wizrocket.atlassian.net/browse/MC-1886)
- When app is opened from killed state with push notification and app is using AppDelegate file only, push notification is handled twice - one from Leanplum wrapper side and one from CleverTap side. 
- When app is using SceneDelegate along with AppDelegate file, push is handled once as expected from Leanplum wrapper side. The main reason for this is after iOS v13.0 the `launchOptions` in `didFinishLaunchingWithOptions` method will be nil while using SceneDelegate, so CleverTap doesn't handle push notification for this case. 
- Added boolean `handlePushNotificationFromCleverTap` which …
> Fixes push notification handled twice when app is using AppDelegate only.

- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/MigrationManager+API.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/CTWrapper.swift
- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/Wrapper/Wrapper.swift
JIRA Issue        | [MC-2004](https://wizrocket.atlassian.net/browse/MC-2004)
Remove the info parameter from events and states tracked in CleverTap through the Wrapper.
> Remove event property info from CT Wrapper

- LeanplumSDK/LeanplumSDK/ClassesSwift/Migration/LPCTNotificationsManager.swift
JIRA Issue        | [MC-1886](https://wizrocket.atlassian.net/browse/MC-1886)
People Involved   | @nzagorchev @nishant-clevertap 
Revert "Fixes CT push notification handled twice when app is using AppDelegate only. (#591)"
This reverts commit 04ebab0e81546b2abf39eb162521a6220f2855e1.
The change in the above commit leads to regression. If the app launch (didFinishLaunchingWithOptions) takes a bit more time (for example, on wrappers like ReactNative or Unity), the push notification open is not handled _at all_. The notification is not handled by Leanplum since it is left to CleverTap to handle it (the change in the commit). However, at that point, the application has become active and CleverTap does …
> Revert "Fixes CT push notification handled twice"
